## Settings
title: "anshdaviddev.com"
owner: "ironwolf1990"
url: "https://anshdaviddev.com"
# baseurl: "/blog" # the subpath of your site, e.g. "/blog"
baseurl: ""
permalink: /:year/:month/:day/:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

## Global Variables
email: "ansh1990@gmail.com"
github: "ironWolf1990"
linkedin: "ansh-david-071b0354"

# path to: css/, fonts/, img/ and js/

assets_path: "/assets"
statement: "Designed by DeerRIDER, [akiritsu/pRoJEct-NeGYa (Github)]. All Rights Reserved"

toc_level: 6

# texts randomly displayed in background
bgtext: "ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴ\
        ふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわゐゑをんゔゕゖァアィイゥウェエォオカガキギクグケゲコゴ\
        サザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリ\
        ルレロヮワヰヱヲンヴヵヶヷヸヹヺ・ーヽヾヿ"

plugins:
  - jekyll-sitemap